version: '3'

services:
  pg:
    image: postgres # use latest official postgres version
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down


volumes:
  pg-data:
